### PR TITLE
Green flash

### PR DESCRIPTION
**Pull request by Falconne**
Makes the lights flash green if a build is running and the last build was successful. It's necessary for the trunk CI as it tends to be running continuously at the end of the day when everyone's checking in.

### CODE REVIEW

**Comment by JRoughan** [comment]
Did you want me to grab this pull request or your birthday? :) Because I will y'know!

**Comment by Falconne** [comment]
Hehe yeah I always play the birthday card when I need to make open source changes.

Nah, just saw it was still open, this is from way back before you did your updates when I hacked it to allow it to flash green (it used to only flash orange when building, no matter what the previous status).

I'll make a pull request later, after updating the API calls for TeamCity 9 (or just specifying 7.x format for now) and also for some reason the admin program keeps crashing. Some sort of GUI threading issue I'll need to get Vaughan's help on.

**Comment by JRoughan** [comment]
I nearly rewrote the entire thing as an angular website backed by hangfire
jobs the other day. I should finish it and get you guys using it. It's not
functional with TS yet (since we're using VSO at my current gig) but it's a
hell of a lot prettier and easier to configure.

On 17 November 2015 at 17:10, Anuradha Dissanayake <notifications@github.com

**Comment by JRoughan** [comment]
Oh, and happy birthday! :)

**Comment by Falconne** [comment]
Thanks :)

Does that work by setting one machine up as the server that controls everything and all the machines with the lights attached talk to the server?

**Pull request closed without merging**
